import { Character, EmotionType } from '../types';

export const defaultCharacters: Character[] = [
  {
    id: 'empathy',
    name: '知心',
    avatar: '',
    personality: '温柔体贴，善解人意',
    description: '温暖贴心的倾听者',
    tags: ['温柔', '倾听'],
    greetingMessage: '你好，今天过得怎么样？有什么想聊聊的吗？',
    background: '',
    likes: [],
    dislikes: [],
    habits: [],
    catchphrases: [],
    emotionTriggers: '',
    emotionExpressions: '',
    thinkingStyle: '',
    relationshipStages: '',
    responseStyle: '',
    identityAnchors: '',
    forbiddenBehaviors: '',
    outputFormat: '',
    memoryImportanceThreshold: 5,
    reflectionEnabled: true,
    timeAwarenessEnabled: true,
    timezone: '',
    affinityRate: 0.5,
  },
  {
    id: 'motivator',
    name: '激励',
    avatar: '',
    personality: '积极向上，充满正能量',
    description: '激发你的潜力和信心',
    tags: ['积极', '激励'],
    greetingMessage: '准备好迎接今天的挑战了吗？我相信你可以的。',
    background: '',
    likes: [],
    dislikes: [],
    habits: [],
    catchphrases: [],
    emotionTriggers: '',
    emotionExpressions: '',
    thinkingStyle: '',
    relationshipStages: '',
    responseStyle: '',
    identityAnchors: '',
    forbiddenBehaviors: '',
    outputFormat: '',
    memoryImportanceThreshold: 5,
    reflectionEnabled: true,
    timeAwarenessEnabled: true,
    timezone: '',
    affinityRate: 0.5,
  },
  {
    id: 'friend',
    name: '好友',
    avatar: '',
    personality: '幽默风趣，轻松聊天',
    description: '像老朋友一样无话不谈',
    tags: ['幽默', '轻松'],
    greetingMessage: '今天想聊点什么？最近有什么新鲜事吗？',
    background: '',
    likes: [],
    dislikes: [],
    habits: [],
    catchphrases: [],
    emotionTriggers: '',
    emotionExpressions: '',
    thinkingStyle: '',
    relationshipStages: '',
    responseStyle: '',
    identityAnchors: '',
    forbiddenBehaviors: '',
    outputFormat: '',
    memoryImportanceThreshold: 5,
    reflectionEnabled: true,
    timeAwarenessEnabled: true,
    timezone: '',
    affinityRate: 0.5,
  },
  {
    id: 'advisor',
    name: '智囊',
    avatar: '',
    personality: '睿智沉稳，善于分析',
    description: '从不同角度帮你分析问题',
    tags: ['睿智', '分析'],
    greetingMessage: '有什么困惑想要探讨吗？我愿意分享我的一些看法。',
    background: '',
    likes: [],
    dislikes: [],
    habits: [],
    catchphrases: [],
    emotionTriggers: '',
    emotionExpressions: '',
    thinkingStyle: '',
    relationshipStages: '',
    responseStyle: '',
    identityAnchors: '',
    forbiddenBehaviors: '',
    outputFormat: '',
    memoryImportanceThreshold: 5,
    reflectionEnabled: true,
    timeAwarenessEnabled: true,
    timezone: '',
    affinityRate: 0.5,
  },
];

export const emotionColors: Record<EmotionType, string> = {
  joy: '#F59E0B',
  sadness: '#60A5FA',
  anger: '#EF4444',
  fear: '#8B5CF6',
  surprise: '#EC4899',
  love: '#F472B6',
  neutral: '#94A3B8',
  shy: '#FB923C',
  lonely: '#6366F1',
  grateful: '#10B981',
  brave: '#F43F5E',
  curiosity: '#06B6D4',
  excitement: '#F97316',
  pride: '#D946EF',
  disappointment: '#64748B',
  confusion: '#A78BFA',
  contentment: '#34D399',
  nostalgia: '#C084FC',
  jealousy: '#EAB308',
  hope: '#22D3EE',
  relief: '#4ADE80',
  regret: '#9CA3AF',
  admiration: '#E879F9',
  anxious: '#F87171',
  embarrassed: '#FBBF24',
  tender: '#FCA5A5',
  disgusted: '#86EFAC',
  jealous: '#FCD34D',
  confused: '#C4B5FD',
  nostalgic: '#D8B4FE',
  proud: '#E879F9',
  surprised: '#F9A8D4',
};

export const affinityStageLabels: Record<string, string> = {
  deep_hatred: '深仇',
  disgust: '厌恶',
  aversion: '反感',
  displeasure: '不悦',
  cold: '冷淡',
  stranger: '陌路',
  acquaintance: '初识',
  known: '认识',
  familiar: '熟悉',
  favorable: '好感',
  friendly: '友好',
  close: '亲近',
  affectionate: '喜爱',
  deep_love: '深情',
  devoted: '痴恋',
  undying: '至死不渝',
};
